Add rockcraft cache

diff --git a/.github/workflows/build_rocks.yaml b/.github/workflows/build_rocks.yaml
--- a/.github/workflows/build_rocks.yaml
+++ b/.github/workflows/build_rocks.yaml
@@ -25,6 +25,9 @@ on:
         type: string
         description: The working directory for jobs
         default: "./"
+      cache-action:
+        type: string
+        description: The cache action can either be "save" or "restore".
     outputs:
       images:
         description: List of images built
@@ -38,6 +41,12 @@ jobs:
       rock-paths: ${{ env.ROCK_PATHS }}
       rocks: "${{ env.ROCKS }}"
     steps:
+      - name: Validate inputs
+        run: |
+          if [ "${{ inputs.cache-action }}" != "save" ] && [ "${{ inputs.cache-action }}}" != "restore" ]; then
+            echo "Invalid value for cache-action. It must be 'save' or 'restore'"
+            exit 1
+          fi
       - uses: actions/checkout@v3
       - name: Get rock paths
         working-directory: ${{ inputs.working-directory }}
@@ -60,16 +69,48 @@ jobs:
         path: ${{ fromJSON(needs.get-rocks.outputs.rock-paths) }}
     steps:
       - uses: actions/checkout@v3
+      - name: Extract rock information
+        run: |
+          IMAGE_NAME=$(yq '.name' "${{ matrix.path }}/rockcraft.yaml")
+          IMAGE_BASE=$(yq '.base' "${{ matrix.path }}/rockcraft.yaml")
+          IMAGE_BUILD_BASE=$(yq '.["build-base"] // .base' "${{ matrix.path }}/rockcraft.yaml")
+          IMAGE_REF=${{ inputs.registry }}/${{ inputs.owner }}/$IMAGE_NAME:${{ github.run_id }}
+          INODE_NUM=$(ls -id ${{ matrix.path }} | cut -f 1 -d " ")
+          ROCKCRAFT_CONTAINER_NAME=rockcraft-${{ env.IMAGE_NAME }}-$INODE_NUM
+          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
+          echo "IMAGE_BASE=$IMAGE_BASE" >> $GITHUB_ENV
+          echo "IMAGE_BUILD_BASE=$IMAGE_BUILD_BASE" >> $GITHUB_ENV
+          echo "IMAGE_REF=$IMAGE_REF" >> $GITHUB_ENV
+          echo "ROCKCRAFT_CONTAINER_NAME=$ROCKCRAFT_CONTAINER_NAME" >> $GITHUB_ENV
+      - name: Generate rockcraft cache key          
+        run: |
+          ROCKCRAFT_CACHE_KEY='rockcraft-cache+name:${{ env.IMAGE_NAME }}+base:${{ env.IMAGE_BUILD_BASE }}+build-base:${{ env.IMAGE_BUILD_BASE }}'
+          echo "ROCKCRAFT_CACHE_KEY=$ROCKCRAFT_CACHE_KEY" >> $GITHUB_ENV
+      - name: Restore rockcraft container cache
+        if: ${{ inputs.cache-action }} == "restore" 
+        uses: actions/cache/restore@v3
+        id: rockcraft-cache
+        with:
+          path: ~/.rockcraft-cache/
+          key: ${{ env.ROCKCRAFT_CACHE_KEY }}
+      - name: Import rockcraft container cache
+        if: steps.rockcraft-cache.outputs.cache-hit == 'true'
+        run: |
+          sudo lxc --project rockcraft import ~/.rockcraft-cache/${{ env.IMAGE_NAME }}.tar ${{ env.ROCKCRAFT_CONTAINER_NAME }}
       - name: Build rock
         uses: canonical/craft-actions/rockcraft-pack@main
         with:
           path: ${{ matrix.path }}
-      - name: Extract rock information
+      - name: Generate rockcraft container cache
+        if: ${{ inputs.cache-action }} == "save"
         run: |
-          IMAGE_NAME=$(yq '.name' "${{ matrix.path }}/rockcraft.yaml")
-          IMAGE_REF=${{ inputs.registry }}/${{ inputs.owner }}/$IMAGE_NAME:${{ github.run_id }}
-          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
-          echo "IMAGE_REF=$IMAGE_REF" >> $GITHUB_ENV
+          sudo lxc --project rockcraft ${{ env.ROCKCRAFT_CONTAINER_NAME }} --compression none ~/.rockcraft-cache/${{ env.IMAGE_NAME }}.tar
+      - name: Save rockcraft container cache
+        if: ${{ inputs.cache-action }} == "save"
+        uses: actions/cache/save@v3
+        with:
+          path: ${{ matrix.path }}
+          key: ${{ env.ROCKCRAFT_CACHE_KEY }}
       - name: Upload rock to ghcr.io
         run: |
           skopeo --insecure-policy copy oci-archive:$(ls "${{ matrix.path }}"/*.rock) docker://$IMAGE_REF --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}"
