set no default for runs-on

diff --git a/.github/workflows/integration_test.yaml b/.github/workflows/integration_test.yaml
--- a/.github/workflows/integration_test.yaml
+++ b/.github/workflows/integration_test.yaml
@@ -90,8 +90,7 @@ on:
         default: "dns ingress rbac storage"
       runs-on:
         type: string
-        description: Image of the runner to run the test job. This gets ignored if self-hosted-runner is set to true.
-        default: ubuntu-22.04
+        description: Image of the GitHub hosted runner to run the test job. This cannot be combined with self-hosted-runner=true.
       self-hosted-runner:
         type: boolean
         description: Whether to use self-hosted runners to run the jobs.
@@ -209,11 +208,10 @@ jobs:
       - name: Validate input
         run: |
           # exit if runs-on and self-hosted-runner is both set
-          if [ "${{ inputs.runs-on }}" != "ubuntu-22.04" ] && [ ${{ inputs.self-hosted-runner }} == true ]
-          then
-              echo "::error Both runs-on and self-hosted-runner cannot be set at the same time."
-              exit 1
-          fi
+            if [ -n "${{ inputs.runs-on }}" ] && [ "${{ inputs.self-hosted-runner }}" = "true" ]; then
+                echo "::error Both runs-on and self-hosted-runner cannot be set at the same time."
+                exit 1
+            fi
       - uses: actions/checkout@v4.2.2
       - uses: canonical/operator-workflows/internal/plan@main
         id: plan
@@ -347,7 +345,7 @@ jobs:
       pre-run-script: ${{ inputs.pre-run-script }}
       provider: ${{ inputs.provider }}
       registry: ghcr.io
-      runs-on: ${{ inputs.runs-on }}
+      runs-on: ${{ inputs.runs-on }} || "ubuntu-22.04"
       self-hosted-runner-arch: ${{ inputs.self-hosted-runner-arch }}
       self-hosted-runner-image: ${{ inputs.self-hosted-runner-image }}
       self-hosted-runner-label: ${{ inputs.self-hosted-runner-label }}
