validate input

diff --git a/.github/workflows/integration_test.yaml b/.github/workflows/integration_test.yaml
--- a/.github/workflows/integration_test.yaml
+++ b/.github/workflows/integration_test.yaml
@@ -206,6 +206,14 @@ jobs:
     outputs:
       plan: ${{ steps.plan.outputs.plan }}
     steps:
+      - name: Validate input
+        run: |
+          # exit if runs-on and self-hosted-runner is both set
+          if [ "${{ inputs.runs-on }}" != "ubuntu-22.04" ] && [ ${{ inputs.self-hosted-runner }} == true ]
+          then
+              echo "::error Both runs-on and self-hosted-runner cannot be set at the same time."
+              exit 1
+          fi
       - uses: actions/checkout@v4.2.2
       - uses: canonical/operator-workflows/internal/plan@main
         id: plan
