fix issues

diff --git a/.github/workflows/promote_charm.yaml b/.github/workflows/promote_charm.yaml
--- a/.github/workflows/promote_charm.yaml
+++ b/.github/workflows/promote_charm.yaml
@@ -41,6 +41,10 @@ on:
         type: string
         description: The working directory for jobs
         default: "./"
+      charmcraft-channel:
+        description: Charmcraft channel to use for promoting the charm.
+        type: string
+        default: latest/stable
 
 jobs:
   validate-channels:
@@ -59,13 +63,18 @@ jobs:
   get-charm-base:
     name: Get charm base
     runs-on: ubuntu-24.04
+    env:
+      CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
     outputs:
-      name: ${{ env.BASE_NAME }}
-      channel: ${{ env.BASE_CHANNEL }}
-      architecture: ${{ env.BASE_ARCHITECTURE }}
-      charm-name: ${{ env.CHARM_NAME }}
+      name: ${{ steps.set-base-outputs.outputs.name }}
+      channel: ${{ steps.set-base-outputs.outputs.channel }}
+      architecture: ${{ steps.set-base-outputs.outputs.architecture }}
     steps:
       - uses: actions/checkout@v4.2.2
+      - name: Install charmcraft
+        run: |
+          set -e
+          sudo snap install charmcraft --classic --channel ${{ inputs.charmcraft-channel }}
       - name: Get charm name
         working-directory: ${{ inputs.working-directory }}/${{ inputs.charm-directory }}
         run: |
@@ -82,8 +91,7 @@ jobs:
           fi
           echo "CHARM_NAME=$CHARM_NAME" >> $GITHUB_ENV
 
-      - uses: actions/checkout@v4.2.2
-      - name: Get charm base
+      - name: Get default charm base
         working-directory: ${{ inputs.working-directory }}/${{ inputs.charm-directory }}
         run: |
           status_json=$(charmcraft status "$CHARM_NAME" --format json)
@@ -97,63 +105,57 @@ jobs:
           echo "BASE_NAME=$BASE_NAME" >> $GITHUB_ENV
           echo "BASE_CHANNEL=$BASE_CHANNEL" >> $GITHUB_ENV
           echo "BASE_ARCHITECTURE=$BASE_ARCHITECTURE" >> $GITHUB_ENV
-  validate-inputs:
-    name: Validate inputs
-    runs-on: ubuntu-24.04
-    outputs:
-      arch: ${{ env.BUILD_ON_ARCH }}
-      channel: ${{ env.BUILD_ON_CHANNEL }}
-      name: ${{ env.BUILD_ON_NAME }}
-    needs: [get-charm-base, validate-channels]
-    steps:
-      - uses: actions/checkout@v4.2.2
-      - run: |
+
+      - name: Validate inputs
+        working-directory: ${{ inputs.working-directory }}/${{ inputs.charm-directory }}
+        run: |
           set -e
 
+          # if input is configured, check if it is present in the charm status
           target_base_arch=${{ inputs.base-architecture }}
           target_base_channel=${{ inputs.base-channel }}
           target_base_name=${{ inputs.base-name }}
 
-          CHARM_NAME=${{ needs.get-charm-base.outputs.charm-name }}
+          [[ -z "$target_base_name" ]] && target_base_name="$BASE_NAME"
+          [[ -z "$target_base_channel" ]] && target_base_channel="$BASE_CHANNEL"
+          [[ -z "$target_base_arch" ]] && target_base_arch="$BASE_ARCHITECTURE"
 
-          # if no input is configured, use the charm base from the previous job
-          if [[ -z "$target_base_channel" ]] && [[ -z "$target_base_name" ]] && [[ -z "$target_base_arch" ]]; then
-            target_base_name=${{ needs.get-charm-base.outputs.name }}
-            target_base_channel=${{ needs.get-charm-base.outputs.channel }}
-            target_base_arch=${{ needs.get-charm-base.outputs.architecture }}
-            echo "BUILD_ON_ARCH=$target_base_arch" >> $GITHUB_ENV
-            echo "BUILD_ON_CHANNEL=$target_base_channel" >> $GITHUB_ENV
-            echo "BUILD_ON_NAME=$target_base_name" >> $GITHUB_ENV
-            exit 0
+          if [[ -n "${{ inputs.base-name }}" || -n "${{ inputs.base-channel }}" || -n "${{ inputs.base-architecture }}" ]]; then
+            status_json=$(charmcraft status "$CHARM_NAME" --format json)
+            track=$(echo "${{ inputs.origin-channel }}" | cut -d '/' -f1)
+
+            mappings=$(echo "$status_json" | jq -c --arg track "$track" '.[] | select(.track == $track) | .mappings[]')
+
+            while IFS= read -r mapping; do
+              base=$(echo "$mapping" | jq -r '.base')
+              name=$(echo "$base" | jq -r '.name')
+              channel=$(echo "$base" | jq -r '.channel')
+              arch=$(echo "$base" | jq -r '.architecture')
+
+              if [[ "$name" == "$target_base_name" && "$channel" == "$target_base_channel" && "$arch" == "$target_base_arch" ]]; then
+                echo "Matched base: $name $channel $arch"
+                echo "BASE_NAME=$name" >> $GITHUB_ENV
+                echo "BASE_CHANNEL=$channel" >> $GITHUB_ENV
+                echo "BASE_ARCHITECTURE=$arch" >> $GITHUB_ENV
+                exit 0
+              fi
+            done <<< "$mappings"
+
+            echo "::error::No matching base found in charm status for: $target_base_name $target_base_channel $target_base_arch"
+            exit 1
+          else
+            echo "No inputs provided for base name, channel, or architecture. Skipping validation."
           fi
-
-          # if input is configured, check if it is present in the charm status
-          status_json=$(charmcraft status "$CHARM_NAME" --format json)
-          track=$(echo "${{ inputs.origin-channel }}" | cut -d '/' -f1)
-          
-          mappings=$(echo "$status_json" | jq -c --arg track "$track" '.[] | select(.track == $track) | .mappings[]')
-          while IFS= read -r mapping; do
-            base=$(echo "$mapping" | jq -r '.base')
-            name=$(echo "$base" | jq -r '.name')
-            channel=$(echo "$base" | jq -r '.channel')
-            arch=$(echo "$base" | jq -r '.architecture')
-
-            if [[ "$name" == "$target_base_name" && "$channel" == "$target_base_channel" && "$arch" == "$target_base_arch" ]]; then
-              echo "Matched base: $name $channel $arch"
-              echo "BUILD_ON_NAME=$name" >> $GITHUB_ENV
-              echo "BUILD_ON_CHANNEL=$channel" >> $GITHUB_ENV
-              echo "BUILD_ON_ARCH=$arch" >> $GITHUB_ENV
-              exit 0
-              break
-            fi
-          done <<< "$mappings"
-
-          echo "::error::No matching base found in charm status for: $target_base_name $target_base_channel $target_base_arch"
-          exit 1
+      - name: Set outputs
+        id: set-base-outputs
+        run: |
+          echo "name=$BASE_NAME" >> $GITHUB_OUTPUT
+          echo "channel=$BASE_CHANNEL" >> $GITHUB_OUTPUT
+          echo "architecture=$BASE_ARCHITECTURE" >> $GITHUB_OUTPUT
   promote-charm:
     name: Promote charm
     runs-on: ubuntu-latest
-    needs: [validate-inputs]
+    needs: [get-charm-base,validate-channels]
     steps:
       - uses: actions/checkout@v4.2.2
       - name: Release charm to channel
@@ -164,9 +166,9 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           origin-channel: ${{ inputs.origin-channel }}
           destination-channel: ${{ inputs.destination-channel }}
-          base-name: ${{ needs.validate-inputs.outputs.name }}
-          base-channel: ${{ needs.validate-inputs.outputs.channel }}
-          base-architecture: ${{ needs.validate-inputs.outputs.arch }}
+          base-name: ${{ needs.get-charm-base.outputs.name }}
+          base-channel: ${{ needs.get-charm-base.outputs.channel }}
+          base-architecture: ${{ needs.get-charm-base.outputs.arch }}
           tag-prefix: ${{ inputs.tag-prefix }}
   publish-docs:
     name: Publish docs
