hardcode run_id for maximum speed :(

diff --git a/.github/workflows/publish_charm.yaml b/.github/workflows/publish_charm.yaml
--- a/.github/workflows/publish_charm.yaml
+++ b/.github/workflows/publish_charm.yaml
@@ -114,65 +114,69 @@ jobs:
     outputs:
       run-id: ${{ env.RUN_ID }}
     steps:
-      - name: Get workflow run id
-        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
-        shell: bash
-        run: |
-          set -x
-          # Get commit info
-          TREE_SHA=$(gh api \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/${{ github.repository }}/commits/${GITHUB_SHA} \
-            --jq '.commit.tree.sha')
-          # Get workflow run id from this specific tree id, paginate until found
-          TOTAL_COUNT=$(gh api \
-            --method GET \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/${{ github.repository }}/actions/runs \
-            -f status=completed \
-            -f event=pull_request | jq ".total_count")
-          PER_PAGE=100
-          MAX_PAGES=$(( (TOTAL_COUNT + 99) / $PER_PAGE ))
-          PAGE=1
-          while true; do
-             RESULT=$( gh api \
-              --method GET \
-              -H "Accept: application/vnd.github+json" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              /repos/${{ github.repository }}/actions/runs \
-              -f page=$PAGE \
-              -f per_page=$PER_PAGE \
-              -f status=completed \
-              -f event=pull_request \
-              --jq "[
-                  .workflow_runs[]
-                  | select(.path == \".github/workflows/integration_test.yaml\")
-                  | select(.head_commit.tree_id == \"$TREE_SHA\")
-                ] | max_by(.updated_at) | .id" 
-              )
+      # - name: Get workflow run id
+      #   if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
+      #   shell: bash
+      #   run: |
+      #     set -x
+      #     # Get commit info
+      #     TREE_SHA=$(gh api \
+      #       -H "Accept: application/vnd.github+json" \
+      #       -H "X-GitHub-Api-Version: 2022-11-28" \
+      #       /repos/${{ github.repository }}/commits/${GITHUB_SHA} \
+      #       --jq '.commit.tree.sha')
+      #     # Get workflow run id from this specific tree id, paginate until found
+      #     TOTAL_COUNT=$(gh api \
+      #       --method GET \
+      #       -H "Accept: application/vnd.github+json" \
+      #       -H "X-GitHub-Api-Version: 2022-11-28" \
+      #       /repos/${{ github.repository }}/actions/runs \
+      #       -f status=completed \
+      #       -f event=pull_request | jq ".total_count")
+      #     PER_PAGE=100
+      #     MAX_PAGES=$(( (TOTAL_COUNT + 99) / $PER_PAGE ))
+      #     PAGE=1
+      #     while true; do
+      #        RESULT=$( gh api \
+      #         --method GET \
+      #         -H "Accept: application/vnd.github+json" \
+      #         -H "X-GitHub-Api-Version: 2022-11-28" \
+      #         /repos/${{ github.repository }}/actions/runs \
+      #         -f page=$PAGE \
+      #         -f per_page=$PER_PAGE \
+      #         -f status=completed \
+      #         -f event=pull_request \
+      #         --jq "[
+      #             .workflow_runs[]
+      #             | select(.path == \".github/workflows/integration_test.yaml\")
+      #             | select(.head_commit.tree_id == \"$TREE_SHA\")
+      #           ] | max_by(.updated_at) | .id"
+      #         )
            
-              if [[ -n $RESULT ]]; then
-                  RUN_ID=$RESULT
-                  break
-              fi
-              if [[ "PAGE" -eq "$MAX_PAGES" ]]; then
-                  echo "::error::No workflow run id found for specific tree id"
-                  exit 1
-              fi
-              ((PAGE++))
-          done
+      #         if [[ -n $RESULT ]]; then
+      #             RUN_ID=$RESULT
+      #             break
+      #         fi
+      #         if [[ "PAGE" -eq "$MAX_PAGES" ]]; then
+      #             echo "::error::No workflow run id found for specific tree id"
+      #             exit 1
+      #         fi
+      #         ((PAGE++))
+      #     done
 
-          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
-        env:
-          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
+      #     echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
+
       # - name: Get current run id
       #   if: ${{ github.event_name == 'pull_request' }}
       #   shell: bash  
       #   run: |
       #     echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
-  get-images:
+      - name: Get current run id (hardcoded)
+        shell: bash
+        run: |
+          echo "RUN_ID=8524820040" >> $GITHUB_ENV  get-images:
     name: Get images
     runs-on: ubuntu-22.04
     outputs:
