fix workflow

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -142,18 +142,25 @@ jobs:
       - name: Resolve Vale file paths
         id: resolve_vale_files
         run: |
+          set -x  # trace commands
           shopt -s globstar nullglob
-          patterns='${{ inputs.vale-files }}'
-          working_directory="$(echo "${{ inputs.working-directory }}" | sed 's:/*$::')"
+
+          patterns='["docs/", "README.md"]'
+          working_directory="$(echo "tests/workflows/integration/test-upload-charm/" | sed 's:/*$::')"
 
           files=$(echo "$patterns" | jq -r '.[]' | while read -r pattern; do
+            echo "Checking pattern: $working_directory/$pattern" >&2
             for f in $working_directory/$pattern; do
+              echo "  candidate: $f" >&2
               [ -e "$f" ] && echo "$f"
             done
-          done | jq -R -s -c 'split("\n")[:-1]')
+          done | jq -R -s -c 'split("\n")[:-1]' ) || {
+            echo "jq failed with input above" >&2
+            exit 1
+          }
 
           echo "Files identified for Vale check: $files"
-          echo "files=$files" >> $GITHUB_OUTPUT
+          echo "files=$files" >> "$GITHUB_OUTPUT"
       - name: Run Vale tests
         uses: errata-ai/vale-action@v2.1.1
         with:
