Debug GitHub workflows

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -92,81 +92,81 @@ jobs:
   get-runner-image:
     name: Get runner image
     uses: ./.github/workflows/get_runner_image.yaml
-  shellcheck-lint:
-    name: Shell scripts lint
-    needs: convert-runner-labels
-    runs-on: ${{ fromJSON(needs.convert-runner-labels.outputs.labels) }}
-    defaults:
-      run:
-        working-directory: ${{ inputs.working-directory }}
-    steps:
-      - uses: actions/checkout@v3
-      - name: Gather files to scan
-        shell: bash
-        id: gather
-        run: |
-          declare -a filepaths
-          shebangregex="^#! */[^ ]*/(env *)?[abk]*sh"
+  # shellcheck-lint:
+  #   name: Shell scripts lint
+  #   needs: convert-runner-labels
+  #   runs-on: ${{ fromJSON(needs.convert-runner-labels.outputs.labels) }}
+  #   defaults:
+  #     run:
+  #       working-directory: ${{ inputs.working-directory }}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Gather files to scan
+  #       shell: bash
+  #       id: gather
+  #       run: |
+  #         declare -a filepaths
+  #         shebangregex="^#! */[^ ]*/(env *)?[abk]*sh"
 
-          set -f # temporarily disable globbing so that globs in inputs aren't expanded
+  #         set -f # temporarily disable globbing so that globs in inputs aren't expanded
 
-          while IFS= read -r -d '' file; do
-          filepaths+=("$file")
-          done < <(find . \
-                        -type f \
-                        '(' \
-                        -name '*.bash' \
-                        -o -name '.bashrc' \
-                        -o -name 'bashrc' \
-                        -o -name '.bash_aliases' \
-                        -o -name '.bash_completion' \
-                        -o -name '.bash_login' \
-                        -o -name '.bash_logout' \
-                        -o -name '.bash_profile' \
-                        -o -name 'bash_profile' \
-                        -o -name '*.ksh' \
-                        -o -name 'suid_profile' \
-                        -o -name '*.zsh' \
-                        -o -name '.zlogin' \
-                        -o -name 'zlogin' \
-                        -o -name '.zlogout' \
-                        -o -name 'zlogout' \
-                        -o -name '.zprofile' \
-                        -o -name 'zprofile' \
-                        -o -name '.zsenv' \
-                        -o -name 'zsenv' \
-                        -o -name '.zshrc' \
-                        -o -name 'zshrc' \
-                        -o -name '*.sh' \
-                        -o -path '*/.profile' \
-                        -o -path '*/profile' \
-                        -o -name '*.shlib' \
-                        ')' \
-                        -print0)
+  #         while IFS= read -r -d '' file; do
+  #         filepaths+=("$file")
+  #         done < <(find . \
+  #                       -type f \
+  #                       '(' \
+  #                       -name '*.bash' \
+  #                       -o -name '.bashrc' \
+  #                       -o -name 'bashrc' \
+  #                       -o -name '.bash_aliases' \
+  #                       -o -name '.bash_completion' \
+  #                       -o -name '.bash_login' \
+  #                       -o -name '.bash_logout' \
+  #                       -o -name '.bash_profile' \
+  #                       -o -name 'bash_profile' \
+  #                       -o -name '*.ksh' \
+  #                       -o -name 'suid_profile' \
+  #                       -o -name '*.zsh' \
+  #                       -o -name '.zlogin' \
+  #                       -o -name 'zlogin' \
+  #                       -o -name '.zlogout' \
+  #                       -o -name 'zlogout' \
+  #                       -o -name '.zprofile' \
+  #                       -o -name 'zprofile' \
+  #                       -o -name '.zsenv' \
+  #                       -o -name 'zsenv' \
+  #                       -o -name '.zshrc' \
+  #                       -o -name 'zshrc' \
+  #                       -o -name '*.sh' \
+  #                       -o -path '*/.profile' \
+  #                       -o -path '*/profile' \
+  #                       -o -name '*.shlib' \
+  #                       ')' \
+  #                       -print0)
 
-          while IFS= read -r -d '' file; do
-          head -n1 "$file" | grep -Eqs "$shebangregex" || continue
-          filepaths+=("$file")
-          done < <(find . \
-                        -type f ! -name '*.*' -perm /111 \
-                        -print0)
-          echo "filepaths=${filepaths[@]}" >> $GITHUB_OUTPUT
-          set +f # re-enable globbing
-      - if: ${{ steps.gather.outputs.filepaths != '' }}
-        name: Shellcheck Problem Matchers
-        uses: lumaxis/shellcheck-problem-matchers@v1.1.2
-      - if: ${{ steps.gather.outputs.filepaths != '' }}
-        run: shellcheck -f gcc ${{steps.gather.outputs.filepaths}}
-      # TODO: For debugging.
-      - name: Setup tmate session
-        uses: mxschmitt/action-tmate@v3
-        if: ${{ failure() }}
-        with:
-          limit-access-to-actor: true
-      - name: Sleep
-        if: ${{ failure() }}
-        run: sleep 6h
-        shell: bash
+  #         while IFS= read -r -d '' file; do
+  #         head -n1 "$file" | grep -Eqs "$shebangregex" || continue
+  #         filepaths+=("$file")
+  #         done < <(find . \
+  #                       -type f ! -name '*.*' -perm /111 \
+  #                       -print0)
+  #         echo "filepaths=${filepaths[@]}" >> $GITHUB_OUTPUT
+  #         set +f # re-enable globbing
+  #     - if: ${{ steps.gather.outputs.filepaths != '' }}
+  #       name: Shellcheck Problem Matchers
+  #       uses: lumaxis/shellcheck-problem-matchers@v1.1.2
+  #     - if: ${{ steps.gather.outputs.filepaths != '' }}
+  #       run: shellcheck -f gcc ${{steps.gather.outputs.filepaths}}
+  #     # TODO: For debugging.
+  #     - name: Setup tmate session
+  #       uses: mxschmitt/action-tmate@v3
+  #       if: ${{ failure() }}
+  #       with:
+  #         limit-access-to-actor: true
+  #     - name: Sleep
+  #       if: ${{ failure() }}
+  #       run: sleep 6h
+  #       shell: bash
   docker-lint:
     name: Dockerfile lint
     needs: convert-runner-labels
