change tox linting to be based on running tox

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -17,11 +17,11 @@ on:
           The outcome of the metadata.yaml linting, mainly for the puposes of the tests for this
           workflow
         value: ${{ jobs.metadata-lint.outputs.outcome }}
-      tox-lint-outcome:
+      lint-and-unit-test-outcome:
         description: |
-          The outcome of the tox.ini linting, mainly for the puposes of the tests for this
+          The outcome of the linting and unit testing, mainly for the puposes of the tests for this
           workflow
-        value: ${{ jobs.tox-lint.outputs.outcome }}
+        value: ${{ jobs.lint-and-unit-test.outputs.outcome }}
 
 jobs:
   inclusive-naming-check:
@@ -230,6 +230,8 @@ jobs:
     name: Lint and unit tests
     runs-on: ${{ needs.get-runner-image.outputs.runs-on }}
     needs: get-runner-image
+    outputs:
+      outcome: ${{ steps.report.outputs.outcome }}
     defaults:
       run:
         working-directory: ${{ inputs.working-directory }}
@@ -238,7 +240,54 @@ jobs:
       - name: Install tox
         run: python3 -m pip install tox
       - name: Run tests
-        run: tox --result-json=test-result.json
+        run: |
+          # Ensure that stdout appears as normal and redirect to file and exit depends on exit code of first command
+          tox --result-json=test-result.json | tee stdout.log ; test ${PIPESTATUS[0]} -eq 0
+      - name: Check lint and test stdout
+        run: |
+          # Check dependencies
+          EXPECTED_LINT_DEPS="\
+              mypy \
+              isort \
+              black \
+              flake8-docstrings \
+              flake8-docstrings-complete \
+              flake8-builtins \
+              flake8-test-docs \
+              pep8-naming \
+              codespell \
+              pylint \
+              pydocstyle \
+              "
+          for EXPECTED_LINT_DEP in $EXPECTED_LINT_DEPS; do
+              # Check that the `lint installed: ` includes the expected dependency
+              DEP_REGEX="lint installed: .*$EXPECTED_LINT_DEP"
+              if ! grep -q "$DEP_REGEX" stdout.log ; then
+                  # Write to stderr
+                  >&2 echo "$EXPECTED_LINT_DEP should be in deps of [testenv:lint] environment in tox.ini"
+                  exit 1
+              fi
+          done
+
+          # Check cmmands
+          EXPECTED_LINT_CMDS="\
+              pydocstyle \
+              codespell \
+              flake8 \
+              isort \
+              black \
+              mypy \
+              pylint \
+              "
+          for EXPECTED_LINT_CMD in $EXPECTED_LINT_CMDS; do
+              # Check that there was a `lint run-test: ` line for the expected command
+              CMD_REGEX="lint run-test: commands\[\d+\] \| $EXPECTED_LINT_CMD"
+              if ! grep -q "$CMD_REGEX" stdout.log ; then
+                  # Write to stderr
+                  >&2 echo "$EXPECTED_LINT_CMD should be in commands of [testenv:lint] environment in tox.ini"
+                  exit 1
+              fi
+          done
       - name: Export test report
         if: always()
         uses: actions/github-script@v6.2.0
@@ -298,6 +347,9 @@ jobs:
         with:
           name: report
           path: report.json
+      - name: Report
+        id: report
+        run: echo "outcome=success" >> $GITHUB_OUTPUT
   draft-publish-docs:
     name: Draft publish docs
     runs-on: ubuntu-22.04
